import './globals.css'
import {Inter} from 'next/font/google';
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en" className={inter.className}>
        <body >
        <NextTopLoader color='#ff0000'/>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    )
}
